// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
public class LogininvaliduserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logininvaliduser() {
    // Test name: Login invalid user
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:3000 |  | 
    driver.get("http://localhost:3000");
    // 2 | setWindowSize | 1366x728 |  | 
    driver.manage().window().setSize(new Dimension(1366, 728));
    // 3 | click | css=.l-GwW:nth-child(1) > .VS-Ex .D8VyR |  | 
    driver.findElement(By.cssSelector(".l-GwW:nth-child(1) > .VS-Ex .D8VyR")).click();
    // 4 | click | css=.VS-Ex:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".VS-Ex:nth-child(2)")).click();
    // 5 | click | css=.\_0cNvO:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".\\_0cNvO:nth-child(2)")).click();
    // 6 | type | id=firstName | sdfsdf | 
    driver.findElement(By.id("firstName")).sendKeys("sdfsdf");
    // 7 | click | id=lastName |  | 
    driver.findElement(By.id("lastName")).click();
    // 8 | type | id=lastName | sdfsdf | 
    driver.findElement(By.id("lastName")).sendKeys("sdfsdf");
    // 9 | click | css=.t1VU0:nth-child(2) > .NI39K |  | 
    driver.findElement(By.cssSelector(".t1VU0:nth-child(2) > .NI39K")).click();
    // 10 | click | id=phone |  | 
    driver.findElement(By.id("phone")).click();
    // 11 | type | id=phone | +380 (11) 11_-__-__ | 
    driver.findElement(By.id("phone")).sendKeys("+380 (11) 11_-__-__");
    // 12 | click | id=registrationConfirmButton |  | 
    driver.findElement(By.id("registrationConfirmButton")).click();
    // 13 | click | css=.\_7Fcq2 |  | 
    driver.findElement(By.cssSelector(".\\_7Fcq2")).click();
  }
}
